// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7ek_hr9NnTKtE0B-XaKPsElPEucUJ3zo',
    appId: '1:860727704154:web:bf737aacaa8cbee3c2f663',
    messagingSenderId: '860727704154',
    projectId: 'login-try-79e0d',
    authDomain: 'login-try-79e0d.firebaseapp.com',
    storageBucket: 'login-try-79e0d.firebasestorage.app',
    measurementId: 'G-9W5D7HC1KL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCns9jn-hsOoOn1OdmMrw9Z3VLjTT3bbBw',
    appId: '1:860727704154:android:f9e3183aaf219312c2f663',
    messagingSenderId: '860727704154',
    projectId: 'login-try-79e0d',
    storageBucket: 'login-try-79e0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa3CWobj8AQ2kvhtQlBSxhOqCi6tNYesA',
    appId: '1:860727704154:ios:5d67dc07c0cecb04c2f663',
    messagingSenderId: '860727704154',
    projectId: 'login-try-79e0d',
    storageBucket: 'login-try-79e0d.firebasestorage.app',
    androidClientId: '860727704154-o9m83i915qua86e43b0nhv03kn1q9c8s.apps.googleusercontent.com',
    iosClientId: '860727704154-nt5dckia5m371chgar06e2ksa8lep63p.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa3CWobj8AQ2kvhtQlBSxhOqCi6tNYesA',
    appId: '1:860727704154:ios:5d67dc07c0cecb04c2f663',
    messagingSenderId: '860727704154',
    projectId: 'login-try-79e0d',
    storageBucket: 'login-try-79e0d.firebasestorage.app',
    androidClientId: '860727704154-o9m83i915qua86e43b0nhv03kn1q9c8s.apps.googleusercontent.com',
    iosClientId: '860727704154-nt5dckia5m371chgar06e2ksa8lep63p.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7ek_hr9NnTKtE0B-XaKPsElPEucUJ3zo',
    appId: '1:860727704154:web:bf737aacaa8cbee3c2f663',
    messagingSenderId: '860727704154',
    projectId: 'login-try-79e0d',
    authDomain: 'login-try-79e0d.firebaseapp.com',
    storageBucket: 'login-try-79e0d.firebasestorage.app',
    measurementId: 'G-9W5D7HC1KL',
  );
}
